#!/bin/bash
set -x -e

#Installing iPython Notebook
if grep isMaster /mnt/var/lib/info/instance.json | grep true;
then
cd /home/hadoop
sudo pip install virtualenv
mkdir -p IPythonNB
cd IPythonNB
/usr/bin/virtualenv -p /usr/bin/python2.7 venv
source venv/bin/activate
# Python will be run from the following /home/hadoop/IPythonNB/venv

#Install ipython and dependencies
pip install "ipython[notebook]"
pip install requests numpy
pip install matplotlib

#Create profile
ipython profile create default

export SPARK_HOME=/usr/lib/spark

echo "c = get_config()" >  /home/hadoop/.ipython/profile_default/ipython_notebook_config.py
echo "c.NotebookApp.ip = '*'" >>  /home/hadoop/.ipython/profile_default/ipython_notebook_config.py
echo "c.NotebookApp.open_browser = False"  >>  /home/hadoop/.ipython/profile_default/ipython_notebook_config.py
echo "c.NotebookApp.port = 8192" >>  /home/hadoop/.ipython/profile_default/ipython_notebook_config.py
mkdir -p /home/hadoop/.ipython/profile_default/startup
wget -P /home/hadoop/.ipython/profile_default/startup https://dsr-notebooks.s3.amazonaws.com/spark-connect.py
ipython notebook --no-browser > /mnt/var/log/python_notebook.log &
fi
